#
# Jekyll serve settings
#

# Reset base to root for localhost development
base:           null

# CDN location for development
file:           http://localhost:4321/
# file:         http://storage.an-aer.bzh/aer

# Force UTF-8 since local server doesn't send charset in their respond header
force_utf_8:    true
